name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ZD_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.ZD_KNOWN_HOSTS }}
          if_key_exists: fail

      - name: SSH into server, pull changes, and build container
        run: |
          ssh -v "$SSH_USERNAME"@zangendeutsch.de "cd /home/"$SSH_USERNAME"/zangendeutsch.de && git pull && docker compose up --build -d"
        env:
          SSH_KEY: ${{ secrets.ZD_SSH_KEY }}
          SSH_USERNAME: ${{ secrets.ZD_USER }}